### ISSUE TITLE
Specify License

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [alovak/test_xml#19]
It would be great if you could add a license file, and specify license used in gemspec - so that licence shows clearly in github, on rubygems.org and can be detected by licence_finder gem.

thanks!

**Comment by sshaw** [comment]
@andrewdavidmackenzie have a look at 35a14c7dbd99f2fd2bf8dda5f0b9422485e1842b. If it's good I'll merge and push to RubyGems.

**Comment by sshaw** [comment]
Fixed in [v0.1.8](https://github.com/alovak/test_xml/tree/v0.1.8).
