### ISSUE TITLE
Identical nodes are not matched correctly

### ISSUE THREAD

**Issue by apotonick** [alovak/test_xml#5]
assert_xml_equal doesn't "see" identical nodes, the following two markup snippets are considered _equal_ in the assertion.

    <wuff>
      <id>1</id>
      <link rel="self" href="http://self"/>
      <link rel="next" href="http://next/1"/>
      <link rel="self" href="http://self"/>
      <link rel="next" href="http://next/1"/>
    </wuff>

==

    <wuff>
      <id>1</id>
      <link rel="self" href="http://self"/>
      <link rel="next" href="http://next/1"/>
    </wuff>

**Comment by alovak** [comment]
was merged.
